In [1]:
import re
import pandas as pd

#### General

In [2]:
df = pd.read_excel('World Dataviz Prize 2023 - Challenge Concepts & Datasets.xlsx',
                   sheet_name="Dashboard of the Present Future", index_col=0)

df

,ISO Country code,population,surface area (Km2),Unnamed: 4,GINI index,happy planet index,happy planet index.1,human development index,human development index.1,sustainable economic development assessment (SEDA),...,Unnamed: 76,CO2e emissions per capita,share of electricity from renewables generation,Unnamed: 79,Unnamed: 80,% of seats held by women in national parliaments,Unnamed: 82,Unnamed: 83,Military Spending as % of GDP,Unnamed: 85
indicator,,,,,,,,,,,,,,,,,,,,,
source,FAO,World Bank Data,CIA World Factbook,NaN,CIA World Factbook,Happy Planet Index,NaN,UNDP,NaN,Boston Consulting Group (BCG),...,NaN,WorldBank,EIA,EIA,NaN,World Bank,WorldBank,WorldBank,SIPRI,SIPRI
URL,http://www.fao.org/countryprofiles/iso3list/en/,https://data.worldbank.org/indicator/SP.POP.TOTL,https://www.cia.gov/library/publications/the-w...,NaN,https://www.cia.gov/library/publications/the-w...,http://happyplanetindex.org/,https://happyplanetindex.org/,http://hdr.undp.org/en/data#,https://hdr.undp.org/data-center/human-develop...,https://www.bcg.com/en-gb/publications/interac...,...,NaN,https://data.worldbank.org/indicator/EN.ATM.CO...,https://www.eia.gov/international/data/world/e...,https://www.eia.gov/international/data/world/e...,NaN,https://data.worldbank.org/indicator/SG.GEN.PA...,https://data.worldbank.org/indicator/SG.GEN.PA...,https://data.worldbank.org/indicator/SG.GEN.PA...,https://milex.sipri.org/sipri,NaN
notes,NaN,NaN,NaN,NaN,inequality in the distribution of family incom...,well being + life expectancy + inequalities + ...,NaN,healthy life + knowledge + standard of living ...,NaN,an assessment based on 40 indicators in sustai...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
data year,2018.0,2018.0,2018.0,NaN,varies by country,2016.0,2019,2017.0,2021,2018.0,...,NaN,2019.0,2015.0,2020 or latest year,NaN,2017.0,2018.0,2021.0,2021.0,2019.0
Afghanistan,AFG,36000000.0,652230.0,NaN,-,20.2,29.4,0.498,0.478,-,...,NaN,0.159824,0.861,0.828087,NaN,27.7,NaN,27.016129,...,0.012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
dfCountries = df[["ISO Country code", "population", "surface area (Km2)",
                  "% of population in extreme poverty",
                  "% of population with access to electricity",
                  "happy planet index", "happy planet index.1",
                  "human development index",	"human development index.1",
                  "unemployment (%)", "Unnamed: 49", "Economic Growth", 
                  "Unnamed: 23"]]

dfCountries

,ISO Country code,population,surface area (Km2),% of population in extreme poverty,% of population with access to electricity,happy planet index,happy planet index.1,human development index,human development index.1,unemployment (%),Unnamed: 49,Economic Growth,Unnamed: 23
indicator,,,,,,,,,,,,,
source,FAO,World Bank Data,CIA World Factbook,WorldBank,WorldBank,Happy Planet Index,NaN,UNDP,NaN,Heritage Foundation,World Bank,WorldBank,WorldBank
URL,http://www.fao.org/countryprofiles/iso3list/en/,https://data.worldbank.org/indicator/SP.POP.TOTL,https://www.cia.gov/library/publications/the-w...,https://data.worldbank.org/topic/poverty,https://data.worldbank.org/indicator/EG.ELC.AC...,http://happyplanetindex.org/,https://happyplanetindex.org/,http://hdr.undp.org/en/data#,https://hdr.undp.org/data-center/human-develop...,https://www.heritage.org/index/explore,https://data.worldbank.org/indicator/SL.UEM.TO...,https://data.worldbank.org/indicator/NY.GDP.MK...,https://data.worldbank.org/indicator/NY.GDP.MK...
notes,NaN,NaN,NaN,NaN,NaN,well being + life expectancy + inequalities + ...,NaN,healthy life + knowledge + standard of living ...,NaN,NaN,NaN,NaN,NaN
data year,2018.0,2018.0,2018.0,latest year,2020.0,2016.0,2019,2017.0,2021,2018.0,2021.0,2018.0,2021 or latest
Afghanistan,AFG,36000000.0,652230.0,0.0,97.699997,20.2,29.4,0.498,0.478,8.5,13.283,1.189228,-2.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.764624,NaN,NaN

#### Countries

In [4]:
dfCountries = dfCountries.rename(columns={"population": "Population" + " (" + 
                            str(dfCountries.loc['data year', 'population']) + ")",
                            "surface area (Km2)": "Surface area (Km2)" + " (" + 
                            str(dfCountries.loc['data year', 'surface area (Km2)'])+ ")",
                            "% of population in extreme poverty": "% of population in extreme poverty" + " (" + 
                            str(dfCountries.loc['data year', '% of population in extreme poverty']) + ")",
                            "% of population with access to electricity": "% of population with access to electricity" + " (" + 
                            str(dfCountries.loc['data year', '% of population with access to electricity']) + ")",
                            "happy planet index": "Happy planet index" + " (" +
                            str(dfCountries.loc['data year', 'happy planet index']) + ")",
                            "happy planet index.1": "Happy planet index" + " (" +
                            str(dfCountries.loc['data year', 'happy planet index.1']) + ")",
                            "human development index": "Human dev index" + " (" +
                            str(dfCountries.loc['data year', 'human development index']) + ")",
                            "human development index.1": "Human dev index" + " (" +
                            str(dfCountries.loc['data year', 'human development index.1']) + ")",
                            "unemployment (%)": "Unemployment (%)" + " (" +
                            str(dfCountries.loc['data year', 'unemployment (%)']) + ")",
                            "Unnamed: 49": "Unemployment (%)" + " (" +
                            str(dfCountries.loc['data year', 'Unnamed: 49']) + ")",
                            "Economic Growth": "Economic Growth" + " (" +
                            str(dfCountries.loc['data year', 'Economic Growth']) + ")",
                            "Unnamed: 23": "Economic Growth" + " (" +
                            str(dfCountries.loc['data year', 'Unnamed: 23']) + ")"
                          })

dfCountries = dfCountries.iloc[4:178]

dfCountries

,ISO Country code,Population (2018.0),Surface area (Km2) (2018.0),% of population in extreme poverty (latest year),% of population with access to electricity (2020.0),Happy planet index (2016.0),Happy planet index (2019),Human dev index (2017.0),Human dev index (2021),Unemployment (%) (2018.0),Unemployment (%) (2021.0),Economic Growth (2018.0),Economic Growth (2021 or latest)
indicator,,,,,,,,,,,,,
Afghanistan,AFG,36000000.0,652230.0,0.0,97.699997,20.2,29.4,0.498,0.478,8.5,13.283,1.189228,-2.35
Albania,ALB,2900000.0,27398.0,0.0,100.0,36.8,51.0,0.785,0.796,16.3,11.819,4.01936,8.544083
Algeria,DZA,41000000.0,2381740.0,NaN,99.804131,33.3,46.5,0.754,0.745,11.2,12.704,1.1,3.847793
Angola,AGO,30000000.0,1246700.0,11.9,46.89061,-,-,0.581,0.586,6.6,8.53,-1.316312,0.7
Argentina,ARG,44000000.0,2736690.0,0.3,100.0,35.2,50.0,0.825,0.842,6.6,10.902,-2.617396,10.263761
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,VEN,32000000.0,882050.0,NaN,100.0,33.6,48.9,0.761,0.691,6.9,6.413,NaN,-
Vietnam,VNM,96000000.0,310070.0,0.2,100.0,40.3,48.4,0.694,0.703,2.2,2.166,7.2,2.588925
Yemen,YEM,28000000.0,527968.0,NaN,73.757927,22.8,44.6,0.452,0.455,17.1,13.574,0.752448,-2.061513
Zambia,ZMB,17000000.0,743398.0,NaN,44.524475,25.2,34.4,0.588,0.565,7.5,13.026,4.034494,3.572815
Zimbabwe,ZWE,17000000.0,386847.0,13.5,52.747669,22.1,28.6,0.535,0.593,5.1,5.174,4.824211,5.84942

In [5]:
dfCountries.to_csv('Countries info.csv', index=True)

#### Comparative metrics

In [6]:
dfCountriesComp = dfCountries[['Happy planet index (2016.0)', 'Happy planet index (2019)',
       'Human dev index (2017.0)', 'Human dev index (2021)',
       'Unemployment (%) (2018.0)', 'Unemployment (%) (2021.0)',
       'Economic Growth (2018.0)', 'Economic Growth (2021 or latest)']]

dfCountriesComp = dfCountriesComp.stack().reset_index(1)
dfCountriesComp.columns = ['Metric', 'Value']
dfCountriesComp

                                       Metric     Value
indicator
Afghanistan       Happy planet index (2016.0)      20.2
Afghanistan         Happy planet index (2019)      29.4
Afghanistan          Human dev index (2017.0)     0.498
Afghanistan            Human dev index (2021)     0.478
Afghanistan         Unemployment (%) (2018.0)       8.5
...                                       ...       ...
Zimbabwe               Human dev index (2021)     0.593
Zimbabwe            Unemployment (%) (2018.0)       5.1
Zimbabwe            Unemployment (%) (2021.0)     5.174
Zimbabwe             Economic Growth (2018.0)  4.824211
Zimbabwe     Economic Growth (2021 or latest)   5.84942

[1383 rows x 2 columns]

In [7]:
dfCountriesComp['Year'] = dfCountriesComp['Metric'].str.extract("(\\d{4})")
dfCountriesComp['Metric'] = dfCountriesComp['Metric'].str.extract("(.*)\(\\d{4}")
dfCountriesComp

                          Metric     Value  Year
indicator
Afghanistan  Happy planet index       20.2  2016
Afghanistan  Happy planet index       29.4  2019
Afghanistan     Human dev index      0.498  2017
Afghanistan     Human dev index      0.478  2021
Afghanistan    Unemployment (%)        8.5  2018
...                          ...       ...   ...
Zimbabwe        Human dev index      0.593  2021
Zimbabwe       Unemployment (%)        5.1  2018
Zimbabwe       Unemployment (%)      5.174  2021
Zimbabwe        Economic Growth   4.824211  2018
Zimbabwe        Economic Growth    5.84942  2021

[1383 rows x 3 columns]

In [8]:
dfCountriesComp.to_csv('Countries info comp.csv', index=True)